{
 "title": "Syncthing Exporter 0.3.7",
 "description": "Dashboard for Syncthing Exporter",
 "tags": [ "syncthing" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "deviceID",
    "label": "deviceID",
    "query": {
     "query": "label_values(syncthing_rest_system_connections_remote_device_connection_info,deviceID)"
    }
   },
   {
    "name": "folderID",
    "label": "folderID",
    "query": {
     "query": "label_values(syncthing_rest_db_status_sequence,folderID)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Syncthing Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "syncthing_rest_svc_report_up" }
   ]
  },
  {
   "title": "Syncthing Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_uptime"
    }
   ]
  },
  {
   "title": "Folders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_number_folders"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_number_devices"
    }
   ]
  },
  {
   "title": "Total number of files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_total_files"
    }
   ]
  },
  {
   "title": "Bytes Transmitted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_total_out_bytes_total"
    }
   ]
  },
  {
   "title": "Total Data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_total_data_in_MB"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_total_in_bytes_total"
    }
   ]
  },
  {
   "title": "Exporter Connected Instance Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_node_info",
     "legendFormat": "{{longVersion}}"
    }
   ]
  },
  {
   "title": "SHA256 Performance value",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_sha256_performance",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory Usage Reported by Syncthing in MB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_memory_usage_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Remote Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Connection Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_connection_info{deviceID=\"$deviceID\"}"
    }
   ]
  },
  {
   "title": "Paused?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_is_paused{deviceID=\"$deviceID\"}"
    }
   ]
  },
  {
   "title": "Bytes Transmitted to Remote",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_out_bytes_total{deviceID=\"$deviceID\"}"
    }
   ]
  },
  {
   "title": "Items by folderID",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "syncthing_rest_db_status_global_total_items{folderID=\"$folderID\"}",
     "legendFormat": "Global total items"
    },
    {
     "expr": "syncthing_rest_db_status_local_total_items{folderID=\"$folderID\"}",
     "legendFormat": "Local total items"
    },
    {
     "expr": "syncthing_rest_db_status_need_total_items{folderID=\"$folderID\"}",
     "legendFormat": "Need total items"
    },
    {
     "expr": "syncthing_rest_db_status_insync_files{folderID=\"$folderID\"}",
     "legendFormat": "Insync Files"
    }
   ]
  },
  {
   "title": "Client version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_connection_info{deviceID=\"$deviceID\"}",
     "legendFormat": "{{clientVersion}}"
    }
   ]
  },
  {
   "title": "Folder state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_db_status_sequence{folderID=\"$folderID\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Bytes Received from Remote",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_in_bytes_total{deviceID=\"$deviceID\"}"
    }
   ]
  },
  {
   "title": "Folder State Changed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_db_status_sequence{folderID=\"$folderID\"}",
     "legendFormat": "{{stateChanged}}"
    }
   ]
  },
  {
   "title": "Crypto configuration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_connection_info{deviceID=\"$deviceID\"}",
     "legendFormat": "{{crypto}}"
    }
   ]
  }
 ]
}