{
 "title": "VerneMQ Cluster TEST",
 "description": "VerneMQ Cluster Metrics\n",
 "tags": [ "MQTT" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "POD",
    "label": "Instance",
    "query": {
     "query": "label_values(vernemq_system_runtime,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(vernemq_system_runtime)" }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vernemq_total_active_connections{pod=~\"$POD\"})"
    }
   ]
  },
  {
   "title": "Queues Processes",
   "type": "stat",
   "description": "This is the current total of living queues (started queue processes). These queues might be in an online or an offline state (ie. belong to an online or offline client).",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vernemq_queue_processes{pod=~\"$POD\"})"
    }
   ]
  },
  {
   "title": "MQTT Receive/Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vernemq_mqtt_publish_received{pod=~\"$POD\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "System Utilization",
   "type": "gauge",
   "description": "VerneMQ Broker average Erlang Scheduler utilization.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(vernemq_system_utilization{pod=~\"$POD\"}) / count(vernemq_system_utilization{pod=~\"$POD\"}))"
    }
   ]
  },
  {
   "title": "Data Ingress",
   "type": "stat",
   "description": "Total bytes into cluster",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vernemq_system_io_in{pod=~\"$POD\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Highest VerneMQ Cluster Broker Uptime",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vernemq_system_wallclock{pod=~\"$POD\"})"
    }
   ]
  },
  {
   "title": "mqtt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vernemq_active_mqtt_connections{pod=~\"$POD\"})"
    }
   ]
  },
  {
   "title": "mqttws",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vernemq_active_mqttws_connections{pod=~\"$POD\"})"
    }
   ]
  },
  {
   "title": "Queue Messages In",
   "type": "stat",
   "description": "Number of PUBLISH packets received by MQTT queue processes.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vernemq_queue_message_in{pod=~\"$POD\"})",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "MQTT Send/Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vernemq_mqtt_publish_sent{pod=~\"$POD\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Data Egress",
   "type": "stat",
   "description": "Total bytes out of cluster",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vernemq_system_io_out{pod=~\"$POD\"})"
    }
   ]
  },
  {
   "title": "CLIENTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connect/Disconnect Rate (per second)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(vernemq_socket_open{pod=~\"$POD\"}[$__rate_interval]))",
       "legendFormat": "Connect (Socket Open) - $POD"
      },
      {
       "expr": "sum(rate(vernemq_socket_close{pod=~\"$POD\"}[$__rate_interval]))",
       "legendFormat": "Disconnect (Socket Close) - $POD"
      }
     ]
    }
   ]
  },
  {
   "title": "QUEUES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Queue Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vernemq_queue_processes{pod=~\"$POD\"}",
       "legendFormat": "Queue Total: {{pod}}"
      }
     ]
    },
    {
     "title": "Queue Setup and Teardown Rate (per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(vernemq_queue_setup{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Queue Setup: {{pod}}"
      },
      {
       "expr": "rate(vernemq_queue_teardown{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Queue Teardown: {{pod}}"
      }
     ]
    },
    {
     "title": "Messages in Queues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(vernemq_queue_message_in{pod=~\"$POD\"}[$__rate_interval]) >0",
       "legendFormat": "In: {{pod}}"
      },
      {
       "expr": "rate(vernemq_queue_message_out{pod=~\"$POD\"}[$__rate_interval]) >0",
       "legendFormat": "Out: {{pod}}"
      },
      {
       "expr": "rate(vernemq_queue_message_drop{pod=~\"$POD\"}[$__rate_interval]) >0",
       "legendFormat": "Dropped: {{pod}}"
      },
      {
       "expr": "rate(vernemq_queue_message_unhandled{pod=~\"$POD\"}[1m]) >0",
       "legendFormat": "Unhandled: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SUBSCRIPTIONS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Router Subscriptions Total",
     "type": "timeseries",
     "description": "Number of subscription in the routing table.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "vernemq_router_subscriptions{pod=~\"$POD\"}",
       "legendFormat": "Subscriptions Total: {{pod}}"
      }
     ]
    },
    {
     "title": "Routing Table Memory",
     "type": "timeseries",
     "description": "Number of bytes used by the routing table.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "vernemq_router_memory{pod=~\"$POD\"}",
       "legendFormat": "Router Memory: {{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "ERLANG VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Average Erlang Scheduler Utilization",
   "type": "timeseries",
   "description": "Scheduler Utilization as Percentage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vernemq_system_utilization{pod=~\"$POD\"}",
     "legendFormat": "System Utilization: {{pod}}"
    }
   ]
  },
  {
   "title": "System Reductions/sec",
   "type": "timeseries",
   "description": "Current Rate of System Reductions.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(vernemq_system_reductions{pod=~\"$POD\"}[$__rate_interval])",
     "legendFormat": "System Reductions: {{pod}}"
    }
   ]
  },
  {
   "title": "Erlang Scheduler Utilization (Top 12)",
   "type": "bargauge",
   "description": "Top Utilized Schedulers by Node Instance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(12,{__name__=~\"vernemq_system_utilization_scheduler_.*\",pod=~\"$POD\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Erlang System Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(vernemq_system_context_switches{pod=~\"$POD\"}[$__rate_interval])",
     "legendFormat": "Erlang Context Switches: {{pod}}"
    }
   ]
  },
  {
   "title": "System IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(vernemq_system_io_in{pod=~\"$POD\"}[$__rate_interval])",
     "legendFormat": "System IO IN: {{pod}}"
    },
    {
     "expr": "rate(vernemq_system_io_out{pod=~\"$POD\"}[$__rate_interval])",
     "legendFormat": "System IO OUT: {{pod}}"
    }
   ]
  },
  {
   "title": "Erlang System Run Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "vernemq_system_run_queue{pod=~\"$POD\"}",
     "legendFormat": "Erlang Run Queue: {{pod}}"
    }
   ]
  },
  {
   "title": "Erlang System Garbage Collection Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(vernemq_system_gc_count{pod=~\"$POD\"}[$__rate_interval])",
     "legendFormat": "Erlang GC Count: {{pod}}"
    }
   ]
  },
  {
   "title": "Erlang System Number of Words Reclaimed by GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rate(vernemq_system_words_reclaimed_by_gc{pod=~\"$POD\"}[$__rate_interval])",
     "legendFormat": "Erlang GC Words Reclaimed: {{pod}}"
    }
   ]
  },
  {
   "title": "BYTES IN & OUT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Received",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(vernemq_bytes_received{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Bytes Received: {{pod}}"
      }
     ]
    },
    {
     "title": "Bytes Sent",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(vernemq_bytes_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Bytes Sent: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RETAIN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Retain Memory use",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "vernemq_retain_memory{pod=~\"$POD\"}",
       "legendFormat": "Retain Memory: {{pod}}"
      }
     ]
    },
    {
     "title": "Retained Messages Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "vernemq_retain_messages{pod=~\"$POD\"}",
       "legendFormat": "Retained Messages: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP SOCKETS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Sockets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "rate(vernemq_socket_open{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Socket Open : {{pod}}"
      },
      {
       "expr": "rate(vernemq_socket_close{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Socket Close : {{pod}}"
      },
      {
       "expr": "rate(vernemq_socket_error{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Socket Error : {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NODE TO CLUSTER COMMUNICATION",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Communication",
     "type": "timeseries",
     "description": "Data rates between cluster nodes.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(vernemq_cluster_bytes_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Bytes Sent: {{pod}}"
      },
      {
       "expr": "rate(vernemq_cluster_bytes_received{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Bytes Received: {{pod}}"
      },
      {
       "expr": "rate(vernemq_cluster_bytes_dropped{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Bytes Dropped: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MQTT CONNECT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTT CONNACK Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_connack_bad_credentials_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Connack Bad Credentials: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_connack_identifier_rejected_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Connack ID rejected: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_connack_not_authorized_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Connack Not Authorized: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_connack_server_unavailable_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Connack Server Unavailable: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_connack_unacceptable_protocol_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Connack Unacceptable Protocol: {{pod}}"
      }
     ]
    },
    {
     "title": "MQTT CONNACK",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_connect_received{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "MQTT CONNECT Received: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_connack_accepted_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "MQTT CONNACK sent: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MQTT SUBSCRIBE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subscribe",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_subscribe_received{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Subscribe Received: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_suback_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "SUBACK sent: {{pod}}"
      }
     ]
    },
    {
     "title": "Unsubscribe",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_unsubscribe_received{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Unsubscribe Received: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_unsuback_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "UNSUBACK sent: {{pod}}"
      }
     ]
    },
    {
     "title": "Subscribe Errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 118 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_subscribe_error{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Subscribe Error: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_subscribe_auth_error{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Subscribe Auth Error: {{pod}}"
      }
     ]
    },
    {
     "title": "Unsubscribe Errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 118 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_unsubscribe_error{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Unsubscribe Error: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MQTT PUBLISH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "QOS 0,1,2: PUBLISH Received, Sent & Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_publish_received{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBLISH Received: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_publish_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBLISH Sent: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_publish_error{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBLISH Error: {{pod}}"
      },
      {
       "expr": "mqtt_vernemq_publish_auth_error{pod=~\"$POD\"}",
       "legendFormat": "PUBLISH Auth Error: {{pod}}"
      }
     ]
    },
    {
     "title": "QOS 1: PUBACK Received, Sent & Invalid",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_puback_received{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBACK Received: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_puback_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBACK Sent: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_puback_invalid_error{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBACK Invalid: {{pod}}"
      }
     ]
    },
    {
     "title": "QOS 2: PUBREC Received, Sent & Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_pubrec_received{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBREC Received: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_pubrec_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBREC Sent: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_pubrec_invalid_error{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBREC Invalid: {{pod}}"
      }
     ]
    },
    {
     "title": "QOS 2: PUBREL Received & Sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_pubrel_received{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBREL Received: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_pubrel_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBREL Sent: {{pod}}"
      }
     ]
    },
    {
     "title": "QOS 2: PUBCOMP Received, Sent & Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_pubcomp_received{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBCOMP Received: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_pubcomp_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBCOMP Sent: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_pubcomp_invalid_error{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PUBCOMP Invalid: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MQTT PING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "PINGREQ & PINGRESP",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_pingreq_received{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PINGREQ Received: {{pod}}"
      },
      {
       "expr": "rate(vernemq_mqtt_pingresp_sent{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "PINGRESP Sent: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MISC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Expired Clients",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "vernemq_client_expired{pod=~\"$POD\"}",
       "legendFormat": "Expired Clients: {{pod}}"
      }
     ]
    },
    {
     "title": "Invalid Message Size Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "rate(vernemq_mqtt_invalid_msg_size_error{pod=~\"$POD\"}[$__rate_interval])",
       "legendFormat": "Invalid Message Size Error: {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}